name: "MixerModel"
input_dim: 3
output_dim: 3
n_encoder: 4
n_decoder: 4
n_feature_enhancer: 0
n_eye_decoder: 4
model_dim: 512
total_dim: 512
n_heads: 8
ff_dim: 2048
max_pos_enc: 15 
max_pos_dec: 26
image_features_dropout: 0
dur_head_dropout: 0.1
end_dropout: 0.1
src_dropout: 0.3
tgt_dropout: 0
reg_head_dropout: 0.1
enh_features_dropout: 0
use_enh_img_features: False
mixed_image_features: False
n_adapter: 2
mixer_dropout: 0
norm_first: True
dropout_p: 0
num_freq_bands: 15
pos_enc_hidden_dim: "${half:${model.model_dim}}" 
input_encoder: "shared_gaussian"
pos_enc_sigma: 1.0
use_rope: False
compilate: False
head_type: "linear"
activation:  "gelu"
word_dropout_prob: 0.3
device: "cuda"
image_encoder:
  enabled: True
  repo_path: "C:\\Users\\ulloa\\OneDrive\\Desktop\\Practicas\\projectes\\dinov3"
  name: "dinov3_vits16"
  weights: "dinov3_vits16_weights.pth"
  freeze: True
  regularization: True
  image_dim: 256
