name: "PathModel"
input_dim: 3
output_dim: 3
n_encoder: 8
n_decoder: 4
model_dim: 512
total_dim: 512
n_heads: 8
ff_dim: 2048
src_dropout: 0
tgt_dropout: 0.3
max_pos_enc: 15
max_pos_dec: 26
norm_first: True
dropout_p: 0
input_encoder: "shared_gaussian"
compilate: False
head_type: "linear"
activation:  "gelu"
device: "cuda"

