# @package _global_
data:
  split_strategy: 
    train_subjects_per: 0.6
training:
  num_epochs: 10
  val_interval: 2
model:
  n_encoder: 2
  n_decoder: 2
  model_dim: 256
  total_dim: 256
  n_heads: 4
  ff_dim: 1024
  n_feature_enhancer: 2
  compilate: False